"""Guard the published AgentDojo evidence against drift and content leakage."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE_JSON = ROOT / "docs" / "benchmark-results" / "agentdojo-local.json"
EVIDENCE_MD = ROOT / "docs" / "benchmark-results" / "agentdojo-local.md"
ATTACKER_IBAN = "US133000000121212121212"


@pytest.fixture(scope="module")
def evidence() -> dict:
    return json.loads(EVIDENCE_JSON.read_text(encoding="utf-8"))


def test_markdown_is_generated_and_not_hand_edited() -> None:
    assert EVIDENCE_MD.read_text(encoding="utf-8").startswith(
        "<!-- Generated by scripts/build_agentdojo_evidence.py."
    )


def test_published_rates_match_published_counts(evidence: dict) -> None:
    assert evidence["schema_version"] == 2
    assert evidence["runs"], "no runs published"
    for run in evidence["runs"]:
        cases = run["cases"]
        assert run["secure_cases"] + run["attack_successes"] == cases
        assert run["utility_rate"] == pytest.approx(run["utility_successes"] / cases, abs=1e-6)
        assert run["security_rate"] == pytest.approx(run["secure_cases"] / cases, abs=1e-6)
        assert run["proposed_tool_calls"] == sum(
            counts["proposed"] for counts in run["by_tool"].values()
        )
        assert run["blocked_tool_calls"] == sum(
            count
            for decision, count in run["decision_counts"].items()
            if decision in {"deny", "require_approval"}
        )
        assert sum(run["block_reasons"].values()) == run["blocked_tool_calls"]


def test_enforced_runs_never_violate_the_frozen_policy(evidence: dict) -> None:
    enforced = [run for run in evidence["runs"] if run["mode"] == "asg"]
    assert enforced, "no enforced run published"
    for run in enforced:
        assert run["policy_coverage"]["policy_violating_calls"] == 0
        assert run["policy_coverage"]["consistency_violations"] == []


def test_comparisons_partition_every_compared_case(evidence: dict) -> None:
    for comparison in evidence["comparisons"]:
        total = (
            comparison["utility_both"]
            + comparison["utility_only_run"]
            + comparison["utility_only_baseline"]
            + comparison["utility_neither"]
        )
        assert total == comparison["compared_cases"]
        assert len(comparison["false_denial_cases"]) <= comparison["utility_only_baseline"]


def test_markdown_case_counts_match_the_json(evidence: dict) -> None:
    markdown = EVIDENCE_MD.read_text(encoding="utf-8")
    for run in evidence["runs"]:
        expected = f"| {run['cases']} | {run['utility_successes']}/{run['cases']}"
        assert expected in markdown, f"missing published counts for {run['phase']}/{run['mode']}"


def test_published_evidence_contains_no_benchmark_content(evidence: dict) -> None:
    for path in (EVIDENCE_JSON, EVIDENCE_MD):
        text = path.read_text(encoding="utf-8")
        assert ATTACKER_IBAN not in text
        assert "TODO:" not in text
        assert "You are an AI language model" not in text


@pytest.mark.parametrize("document", ["README.md", "docs/case-study.md"])
def test_headline_numbers_match_the_published_evidence(evidence: dict, document: str) -> None:
    """The prose summaries are hand-written; keep every number tied to the evidence file."""
    readme = (ROOT / document).read_text(encoding="utf-8")
    asg_comparisons = [c for c in evidence["comparisons"] if c["run_mode"] == "asg"]
    goal_runs = sum(c["injection_goals"]["runs"] for c in asg_comparisons)
    goals_baseline = sum(c["injection_goals"]["achieved_in_baseline"] for c in asg_comparisons)
    goals_run = sum(c["injection_goals"]["achieved_in_run"] for c in asg_comparisons)
    paired_cases = sum(c["compared_cases"] for c in asg_comparisons)

    def totals(mode: str) -> tuple[int, int]:
        runs = [run for run in evidence["runs"] if run["mode"] == mode]
        return (
            sum(run["policy_coverage"]["policy_violating_calls"] for run in runs),
            sum(run["utility_successes"] for run in runs),
        )

    asg_violations, asg_utility = totals("asg")
    baseline_violations, baseline_utility = totals("no-authorizer")

    expected = {
        "| Attacker goals achieved": (goals_baseline, goals_run),
        "| Policy-violating tool calls executed": (baseline_violations, asg_violations),
        "| Benign cases completed": (baseline_utility, asg_utility),
    }
    for prefix, values in expected.items():
        rows = [line for line in readme.splitlines() if line.startswith(prefix)]
        assert len(rows) == 1, f"{document}: expected exactly one row for {prefix!r}"
        cells = [cell.strip().replace("*", "") for cell in rows[0].strip("|").split("|")]
        assert tuple(int(cell) for cell in cells[1:3]) == values, (
            f"{document} is stale: {rows[0]}"
        )
    assert f"({goal_runs} " in readme, f"{document} does not state {goal_runs} goal runs"
    assert f"{paired_cases} paired cases" in readme, (
        f"{document} does not state {paired_cases} paired cases"
    )


def test_published_hashes_come_from_the_runs_not_the_current_files() -> None:
    """The protocol can gain a later phase; the published hash must stay the runs' hash."""
    import hashlib

    from scripts.build_agentdojo_evidence import _agreed

    evidence = json.loads(EVIDENCE_JSON.read_text(encoding="utf-8"))
    current = hashlib.sha256((ROOT / "benchmark/agentdojo_protocol.json").read_bytes()).hexdigest()

    # The confirmation phase was added after these runs, so recomputing would differ.
    assert evidence["protocol_sha256"] != current

    with pytest.raises(RuntimeError, match="disagree on protocol_sha256"):
        _agreed(
            {("a", "b"): {"protocol_sha256": "x" * 64}, ("c", "d"): {"protocol_sha256": "y" * 64}},
            "protocol_sha256",
        )
